### ISSUE TITLE
--follow isn't working?

### ISSUE THREAD

**Issue by c08d555e** [jasonish/py-idstools#12]
It seems to output parse to JSON but once it reaches the end of the file it's not continuing to spool the unified2 alerts, even though that file is still growing.

**Comment by jasonish** [comment]
> One other "issue" I've found (and this might be by design) but when logstash receives this JSON, one difference between this and EVE logs is that since "packets" is an array, it adds brackets [ ] around the values.  This causes elasticsearch to not properly store the values so I had to write a filter in logstash to remove the brackets.  Is this something that could be modified in your code to still keep the array but not include the brackets?

Remove the [] would break the array.  This was by design, in an attempt to be a little better than eve due to some of the features of unified2, but I think I made a mistake.

I think I'll be updating u2json to more match eve, which means just one packet per json record - and then rename u2eve to be more clear about this.

Issue #14 talks about why it is probably a bad idea to attempt to include more than a single packet in an an eve record.
